-- Zeffy hosted checkout correlates stored `checkout_correlation_reference` tokens and final provider ids.

do $$
begin
  if exists (
    select 1
      from information_schema.columns
     where table_schema = 'public'
       and table_name = 'conference_registrations'
       and column_name = 'paystack_reference'
  )
  then
    alter table public.conference_registrations
      rename column paystack_reference to checkout_correlation_reference;
  end if;
end $$;

comment on column public.conference_registrations.checkout_correlation_reference is
  'Before payment completes: opaque checkout correlation token generated by this app. After payment succeeds: persisted Zeffy payment id returned by webhook/API.';

create table if not exists public.provider_payment_audit (
  id uuid primary key default gen_random_uuid(),
  provider text not null default 'zeffy',
  external_payment_id text not null,
  event_type text not null,
  registration_id uuid references public.conference_registrations (id) on delete set null,
  amount_cents integer not null,
  currency text not null default 'USD',
  status text not null,
  payload jsonb not null,
  created_at timestamptz not null default now (),
  constraint provider_payment_audit_provider_external_unique unique (provider, external_payment_id)
);

create index if not exists provider_payment_audit_registration_id_idx on public.provider_payment_audit (registration_id);

comment on table public.provider_payment_audit is 'Immutable payloads from fundraising webhooks/API reconciliation (currently Zeffy).';

alter table public.provider_payment_audit enable row level security;
